changelog:
  categories:
  - title: 💥 Major
    labels:
    - breaking
    - major
  - title: 🚀 Minor
    labels:
    - minor
    - enhancement
    - feature
  - title: 🐛 Patches
    labels:
    - "*"