name: Create Release

on:
  push:
    branches:
      - "main"

jobs:
  init:
    name: Initialize Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Please follow conventional-commits convention on commits.
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: "auto-release"

    