name: Create Release

on:
  push:
    branches:
      - "main"

jobs:
  init:
    name: Initialize Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Please follow conventional-commits convention on commits.
      - uses: google-github-actions/release-please-action@v3

    