name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Sprint Release
        run: |
          echo "Creating release for version ${{ github.ref }}"
          gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    