name: Release

on:
  create:
  push:
    branches:
      # Matches all release branches with the format: release/2023-01
      - 'release/[0-9][0-9][0-9][0-9]-*' 

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - # Please follow conventional-commits convention on commits.
        # https://www.conventionalcommits.org/en/v1.0.0/
        name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: "auto-release"
    

    