name: Scheduled Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: true

jobs:
  release:
    name: Initialize Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.versionName }}
          git push origin release/${{ github.event.inputs.versionName }}
      # Please follow conventional-commits convention on commits.
      # https://www.conventionalcommits.org/en/v1.0.0/
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: "auto-release"

    