name: Update Release

on:
  workflow_dispatch:
    inputs:
      SprintBranchName:
        description: 'Release on Branch Name'
        required: true

jobs:
  release:
    name: Update Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: Checkout to release branch
        run: |
          git fetch --all
          git checkout -b ${{ github.event.inputs.SprintBranchName }}
      # Please follow conventional-commits convention on commits.
      # https://www.conventionalcommits.org/en/v1.0.0/
      - name: Create Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: "auto-release"